### ISSUE TITLE
Fix hourly ACHD value on map with regard to time slider

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/the-shenango-channel#1]
Changes at 30 mins after the hour instead of at the hour

**Comment by rsargent** [comment]
Tested and still happening

**Comment by pdille** [comment]
The ACHD data coming into ESDR has timestamps at the 30min mark. As per this report, should we actually display these values instead at the start of the hour? I don't recall how ACHD is exactly dealing with capture times on their end.

**Comment by pdille** [comment]
Should be fixed in commit 33abc8c0262ba1
