### ISSUE TITLE
Share link

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/the-shenango-channel#2]

**Comment by pdille** [comment]
Was this supposed to be a more elaborate share link or our normal share view? Right now the share view warps the user to that location and subsequently the grapher and map update their values to that specific time. 

Your other request for gifs/videos is certainly the next iteration on share links.

**Comment by rsargent** [comment]
Excellent, that's great.  I guess there's also state of grapher zoom and
map zoom and location.  What do you think about including those on the
share link someday?  Maybe not very high priority.

**Comment by rsargent** [comment]
After further discussion we're not certain grapher zoom and map location are a good thing to share.  We'll hold off until a user actually demonstrates need.
