### ISSUE TITLE
Zoom less when clicking on smell report

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/the-shenango-channel#7]
We lose a lot of context when clicking on a smell report.

Try zooming one level less and make smell note slightly larger font?

**Comment by pdille** [comment]
Good idea and easy to change. When you have a moment, check and let me know what you think of it now.

**Comment by rsargent** [comment]
Definite improvement.

Slight border issue for text:  not enough border at top, too much at bottom?

![image](https://cloud.githubusercontent.com/assets/324851/7238473/b918f36a-e770-11e4-803f-c70b8c5c26f4.png)

**Comment by pdille** [comment]
Ah, looks like the wrong font was being used on Macs. Check again. Verified working on Mac and Windows on my end.

**Comment by rsargent** [comment]
Beautiful!

![image](https://cloud.githubusercontent.com/assets/324851/7241056/153b8834-e784-11e4-9600-4dd54cbbd819.png)
